# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-07 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0004_auto_20190907_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creativity',
            new_name='content',
        ),
    ]
