# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-07 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0005_auto_20190907_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='overall_score',
            new_name='average_score',
        ),
    ]
