# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-07 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_auto_20190907_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='creativity',
            new_name='content',
        ),
    ]
